package com.example.apigrafik.Fragment

data class Stock(
    val meta: Meta,
    val body: List<Body>
)

data class Meta(
    val version: String,
    val status: Int,
    val copywrite: String,
    val symbol: String,
    val processedTime: String
)

data class Body(
    val preMarketChange: Double? = null,
    val preMarketChangePercent: Double? = null,
    val preMarketPrice: Double? = null,
    val preMarketTime: Long? = null,
    val postMarketChange: Double? = null,
    val postMarketChangePercent: Double? = null,
    val postMarketPrice: Double? = null,
    val postMarketTime: Long? = null,
    val language: String = "",
    val region: String = "",
    val quoteType: String = "",
    val typeDisp: String = "",
    val quoteSourceName: String = "",
    val triggerable: Boolean = false,
    val customPriceAlertConfidence: String = "",
    val shortName: String = "",
    val longName: String = "",
    val currency: String = "",
    val marketState: String = "",
    val regularMarketPrice: Double = 0.0,
    val regularMarketTime: Long = 0,
    val hasPrePostMarketData: Boolean = false,
    val firstTradeDateMilliseconds: Long = 0,
    val priceHint: Int = 0,
    val regularMarketChange: Double = 0.0,
    val regularMarketDayHigh: Double = 0.0,
    val regularMarketDayRange: String = "",
    val regularMarketDayLow: Double = 0.0,
    val regularMarketVolume: Long = 0,
    val regularMarketPreviousClose: Double = 0.0,
    val bid: Double = 0.0,
    val ask: Double = 0.0,
    val bidSize: Int = 0,
    val askSize: Int = 0,
    val fullExchangeName: String = "",
    val financialCurrency: String = "",
    val regularMarketOpen: Double = 0.0,
    val averageDailyVolume3Month: Long = 0,
    val averageDailyVolume10Day: Long = 0,
    val fiftyTwoWeekLowChange: Double = 0.0,
    val fiftyTwoWeekLowChangePercent: Double = 0.0,
    val fiftyTwoWeekRange: String = "",
    val fiftyTwoWeekHighChange: Double = 0.0,
    val fiftyTwoWeekHighChangePercent: Double = 0.0,
    val fiftyTwoWeekLow: Double = 0.0,
    val fiftyTwoWeekHigh: Double = 0.0,
    val fiftyTwoWeekChangePercent: Double = 0.0,
    val dividendDate: Long? = null,
    val earningsTimestamp: Long? = null,
    val earningsTimestampStart: Long? = null,
    val earningsTimestampEnd: Long? = null,
    val earningsCallTimestampStart: Long? = null,
    val earningsCallTimestampEnd: Long? = null,
    val isEarningsDateEstimate: Boolean = false,
    val trailingAnnualDividendRate: Double? = null,
    val trailingPE: Double? = null,
    val dividendRate: Double? = null,
    val trailingAnnualDividendYield: Double? = null,
    val dividendYield: Double? = null,
    val epsTrailingTwelveMonths: Double? = null,
    val epsForward: Double? = null,
    val epsCurrentYear: Double? = null,
    val priceEpsCurrentYear: Double? = null,
    val sharesOutstanding: Long? = null,
    val bookValue: Double? = null,
    val fiftyDayAverage: Double? = null,
    val fiftyDayAverageChange: Double? = null,
    val fiftyDayAverageChangePercent: Double? = null,
    val twoHundredDayAverage: Double? = null,
    val twoHundredDayAverageChange: Double? = null,
    val twoHundredDayAverageChangePercent: Double? = null,
    val marketCap: Long? = null,
    val forwardPE: Double? = null,
    val priceToBook: Double? = null,
    val sourceInterval: Int? = null,
    val exchangeDataDelayedBy: Int? = null,
    val averageAnalystRating: String? = null,
    val tradeable: Boolean? = null,
    val cryptoTradeable: Boolean? = null,
    val exchange: String = "",
    val messageBoardId: String = "",
    val exchangeTimezoneName: String = "",
    val exchangeTimezoneShortName: String = "",
    val gmtOffSetMilliseconds: Int = 0,
    val market: String = "",
    val esgPopulated: Boolean = false,
    val regularMarketChangePercent: Double = 0.0,
    val displayName: String = "",
    val symbol: String = ""
)